# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.4'

# Core
gem 'puma', '>= 5.0'
gem 'rails', '~> 8.1.1'

# API essentials
gem 'dotenv-rails'
gem 'faraday', '~> 2.7'
gem 'faraday-retry'
gem 'rack-cors'

# Caching & Performance
gem 'hiredis-client'
gem 'rack-attack'
gem 'redis', '~> 5.0'

# Boot optimization
gem 'bootsnap', require: false

# Windows timezone support
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'brakeman', require: false
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'rubocop-rails-omakase', require: false
end

group :test do
  gem 'mock_redis'
  gem 'vcr'
  gem 'webmock'
end
